# Part of OpenG2P. See LICENSE file for full copyright and licensing details.
{
    "name": "OpenG2P Country Config: ATI",
    "category": "G2P",
    "version": "17.0.1.5.0",
    "sequence": 1,
    "author": "OpenG2P",
    "website": "https://openg2p.org",
    "license": "LGPL-3",
    "depends": ["g2p_social_registry", "g2p_registry_documents", "g2p_enumerator"],
    "external_dependencies": {},
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "data/group_membership_kind.xml",
        "data/id_types.xml",
        "data/regions.xml",
        "data/zones.xml",
        "data/woredas.xml",
        "data/genders.xml",
        "data/crop.xml",
        "data/cooperative_union.xml",
        "data/finance_access.xml",
        "data/crop_illness_types.xml",
        "data/livestock_illness_type.xml",
        "data/income.xml",
        "data/livestock_type.xml",
        "data/machinery_types.xml",
        "data/primary_language.xml",
        "data/primary_commodity.xml",
        "data/water_source.xml",
        "data/import_source.xml",
        "data/season_data.xml",
        "data/crop-variety.xml",
        # "data/farmer_id_cron_job.xml",
        "views/seasons.xml",
        "views/farmer_profile_menu.xml",
        "views/livestock.xml",
        "views/commodity.xml",
        "views/cooperations.xml",
        "views/zone.xml",
        "views/woreda.xml",
        "views/kebele.xml",
        "views/lang.xml",
        "views/machinery.xml",
        "views/illness.xml",
        "views/water_sources.xml",
        "views/hh_income_type.xml",
        "views/res_partner.xml",
        "views/group_membership.xml",
        "views/crop_category.xml",
        "views/crop.xml",
        "views/crop_variety.xml",
        "views/land_info.xml",
        "views/web_login.xml",
        "views/main_menu.xml",
        "views/import_source_views.xml",
        "wizard/rejection_reason_wizard.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "g2p_ati/static/src/components/*",
            "g2p_ati/static/src/components/**/*.js",
            "g2p_ati/static/src/components/**/*.css",
            "g2p_ati/static/src/components/**/*.scss",
            "g2p_ati/static/src/components/**/*.xml",
            "g2p_ati/static/src/js/preview_document.js",
            "g2p_ati/static/src/js/trim_float_field.js",
            "g2p_ati/static/src/js/web_window_title.js",
            "g2p_ati/static/src/xml/preview_document.xml",
        ],
    },
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
