# Part of OpenG2P. See LICENSE file for full copyright and licensing details.
{
    "name": "OpenG2P Service Provider: ATI",
    "category": "G2P",
    "version": "17.0.1.5.0",
    "sequence": 1,
    "author": "OpenG2P",
    "website": "https://openg2p.org",
    "license": "LGPL-3",
    "depends": [
        "g2p_social_registry",
        "g2p_registration_portal_base",
        "g2p_registry_base",
        "g2p_registry_addl_info",
        "g2p_ati",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/dashboard.xml",
        "views/create_group.xml",
        "views/ati_language_dropdown.xml",
        "views/base.xml",
        "views/profile.xml",
        "views/views.xml",
        "views/login.xml",
        "views/create_individual.xml",
        "views/update_individual.xml",
        "views/individual_list.xml",
        "views/create_group.xml",
        "views/group_list.xml",
        "views/update_group.xml",
        "views/ati_portal_update_suggests.xml",
        "views/notification.xml",
        "views/notification_list.xml",
    ],
    "assets": {"web.assets_backend": []},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
    "i18n": ["am_ET", "om_ET"],
}
